# Generated by Django 5.2.12 on 2026-03-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verificacao',
            new_name='Historico',
        ),
    ]
