# Generated by Django 6.0.3 on 2026-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_verificacao_historico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
