# Generated by Django 6.0.3 on 2026-03-21 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_historico_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIPInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('regiao', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=10)),
                ('organizacao', models.CharField(max_length=200)),
                ('timezone', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaVirusTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('malicioso', models.IntegerField()),
                ('inofensivo', models.IntegerField()),
                ('suspeito', models.IntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.AddField(
            model_name='consultavirustotal',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo'),
        ),
        migrations.AddField(
            model_name='consultaipinfo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipo'),
        ),
    ]
